version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the java code...
      - Java StudentControllerIT.java
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - StudentControllerIT.java
